/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ID.java
 *
 * Created on 25 mai 2010, 15:06:32
 */
package MAC;

import java.math.BigInteger;
import javax.swing.*;
import java.math.BigInteger;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author choukri
 */
public class AES extends javax.swing.JFrame {

    /** Creates new form ID */
    
    String algo = "AES";
    int taille = 128;  //AES = 128 et DES = 56
    String cle = "AzertyutAzertyut";
    byte[] Key = cle.getBytes();

    public byte[] generateKey() {
        KeyGenerator key_gen = null;
        try {
            key_gen = KeyGenerator.getInstance(algo);
        } catch (NoSuchAlgorithmException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        key_gen.init(taille);
        return key_gen.generateKey().getEncoded();
    }

    public byte[] crypt(byte[] text) {
        byte[] encrypted = null;
        try {
            Cipher cipher = Cipher.getInstance(algo);
            cipher.init(Cipher.ENCRYPT_MODE, new SecretKeySpec(Key, algo));
            encrypted = cipher.doFinal(text);

        } catch (Exception ex) {
            Logger.getLogger(algorithme.class.getName()).log(Level.SEVERE, null, ex);
        }
        return encrypted;
    }

    public byte[] decrypt(byte[] ciphertext) {
        byte[] decrypted = null;
        try {
            Cipher cipher = Cipher.getInstance(algo); //$NON-NLS-1$
            cipher.init(Cipher.DECRYPT_MODE, new SecretKeySpec(Key, algo));
            decrypted = cipher.doFinal(ciphertext);
        } catch (Exception ex) {
            Logger.getLogger(algorithme.class.getName()).log(Level.SEVERE, null, ex);
        }
        return decrypted;
    }

    public String afficher(byte[] tab) {
        int n = tab.length;
        String x = "";
        for (int i = 0; i < n; i++) {
            x += tab[i] + " ";
        }
        return x + "\n";
    }

    public String ToString(byte[] tab) {
        String x = "";
        int i = tab.length - 1;
        int c;
        while (i >= 0) {
            x = (char) tab[i--] + x;
        }
        return x;
    }

    public String[] decomposer(String texte, int taille) {
        int n = texte.length();
        int k;
        if (n % taille != 0) {
            k = taille - n % taille;
            n += k;
            for (int i = 0; i < k; i++) {
                texte += "0";
            }
        }
        k = n / taille;
        String[] tab = new String[k];
        for (int i = 0; i < k; i++) {
            tab[i] = texte.substring(i * taille, (i + 1) * taille);
        }
        return tab;
    }

    public byte[] Xor(byte[] t1, String t2) {
        return (new BigInteger(t1)).xor(new BigInteger(t2.getBytes())).toByteArray();
    }

    public String Hex(byte[] t) {
        String x = "";
        String y;
        char[] tab = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F'};
        int n = t.length;
        int k;
        for (int i = 0; i < n; i++) {
            k = t[i];
            if (k < 0) {
                k += 256;
            }
            x += tab[k / 16] + "" + tab[k % 16];
        }
        return x;
    }

    public AES() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/testt/logo.png")).getImage());

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        message = new javax.swing.JLabel();
        hmac = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        jtemps = new javax.swing.JLabel();
        txthmac = new javax.swing.JTextField();
        temps = new javax.swing.JTextField();
        fermer = new javax.swing.JButton();
        calculer = new javax.swing.JButton();
        réinitialiser = new javax.swing.JButton();
        txtmessage = new javax.swing.JScrollPane();
        jtxtmessage = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        message.setForeground(new java.awt.Color(51, 153, 255));
        message.setText("Message");
        message.setName("Message"); // NOI18N

        hmac.setForeground(new java.awt.Color(51, 153, 255));
        hmac.setText("CBC-MAC avec AES");

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MAC/scytale.gif"))); // NOI18N
        image.setIconTextGap(0);

        jtemps.setForeground(new java.awt.Color(51, 153, 255));
        jtemps.setText("Temps d'execution");

        txthmac.setForeground(new java.awt.Color(255, 102, 0));

        temps.setEditable(false);
        temps.setForeground(new java.awt.Color(255, 102, 0));

        fermer.setForeground(new java.awt.Color(51, 153, 255));
        fermer.setText("Fermer");
        fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fermerActionPerformed(evt);
            }
        });

        calculer.setForeground(new java.awt.Color(51, 153, 255));
        calculer.setText("Calculer");
        calculer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculerActionPerformed(evt);
            }
        });

        réinitialiser.setForeground(new java.awt.Color(51, 153, 255));
        réinitialiser.setText("Réinitialiser");
        réinitialiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                réinitialiserActionPerformed(evt);
            }
        });

        jtxtmessage.setColumns(20);
        jtxtmessage.setForeground(new java.awt.Color(255, 102, 0));
        jtxtmessage.setRows(5);
        txtmessage.setViewportView(jtxtmessage);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hmac)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txthmac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(message)
                                .addComponent(txtmessage, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(74, 74, 74)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(temps, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                .addComponent(jtemps)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(calculer)
                            .addGap(177, 177, 177)
                            .addComponent(réinitialiser)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                            .addComponent(fermer))))
                .addGap(85, 85, 85))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(image)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(message)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jtemps)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(temps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtmessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(hmac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txthmac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fermer)
                    .addComponent(calculer)
                    .addComponent(réinitialiser))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fermerActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_fermerActionPerformed

    private void réinitialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_réinitialiserActionPerformed
        temps.setText("");
        txthmac.setText("");
        jtxtmessage.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_réinitialiserActionPerformed

    private void calculerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculerActionPerformed
// TODO add your handling code here:
        String msg = jtxtmessage.getText();

        double q = System.nanoTime();

        AES aes = new AES();
        String[] s = aes.decomposer(msg, 10);
        byte[] b = aes.crypt(s[0].getBytes());
        String str;
        int j = 1;
        while (j < s.length) {
            b = aes.crypt(aes.Xor(b, s[j++]));
        }


        txthmac.setText(aes.Hex(b));






        q = System.nanoTime() - q;
        q /= 1000000000;
        temps.setText(q + "  Sec");
    }//GEN-LAST:event_calculerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AES().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculer;
    private javax.swing.JButton fermer;
    private javax.swing.JLabel hmac;
    private javax.swing.JLabel image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jtemps;
    private javax.swing.JTextArea jtxtmessage;
    private javax.swing.JLabel message;
    private javax.swing.JButton réinitialiser;
    private javax.swing.JTextField temps;
    private javax.swing.JTextField txthmac;
    private javax.swing.JScrollPane txtmessage;
    // End of variables declaration//GEN-END:variables
}
