package MAC;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
//import java.awt.*;
//import javax.swing.*;


/*
 * Menu.java
 */
/**
 *
 * @author  choukri
 */
public class Menu extends javax.swing.JFrame {
    //private Thread t;

    /** Creates new form Menu */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/testt/logo.png")).getImage());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ArierPlan = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        HMAC = new javax.swing.JMenu();
        MD5 = new javax.swing.JMenuItem();
        SHA_1 = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        CBC_MAC = new javax.swing.JMenu();
        DES = new javax.swing.JMenuItem();
        AES = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();
        help = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projet MAC");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ArierPlan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MAC/Arier-Application.jpg"))); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(ArierPlan)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(ArierPlan)
        );

        HMAC.setText("HMAC");
        HMAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HMACActionPerformed(evt);
            }
        });

        MD5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        MD5.setText("MD5");
        MD5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        HMAC.add(MD5);

        SHA_1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        SHA_1.setText("SHA-1");
        SHA_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SHA_1ActionPerformed(evt);
            }
        });
        HMAC.add(SHA_1);

        Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        HMAC.add(Exit);

        jMenuBar2.add(HMAC);

        CBC_MAC.setText("CBC-MAC");

        DES.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        DES.setText("DES");
        DES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DESActionPerformed(evt);
            }
        });
        CBC_MAC.add(DES);

        AES.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        AES.setText("AES");
        AES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AESActionPerformed(evt);
            }
        });
        CBC_MAC.add(AES);

        jMenuBar2.add(CBC_MAC);

        Help.setText("Help ?");

        help.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        help.setText("help");
        Help.add(help);

        jMenuBar2.add(Help);

        setJMenuBar(jMenuBar2);
        jMenuBar2.getAccessibleContext().setAccessibleParent(this);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        MD5 a = new MD5();
        a.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void SHA_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHA_1ActionPerformed
        try {

            SHA1 m = new SHA1();
            m.setVisible(true);

        } catch (Exception ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }

}//GEN-LAST:event_SHA_1ActionPerformed

    private void HMACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HMACActionPerformed
}//GEN-LAST:event_HMACActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);

    }//GEN-LAST:event_ExitActionPerformed

    private void DESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DESActionPerformed

        try {

            DES d = new DES();
            d.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_DESActionPerformed

    private void AESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AESActionPerformed

        try {

            AES a = new AES();
            a.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_AESActionPerformed

    /**private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) 
     * @param args the command line arguments
     */
    private void JMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AES;
    private javax.swing.JLabel ArierPlan;
    private javax.swing.JMenu CBC_MAC;
    private javax.swing.JMenuItem DES;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu HMAC;
    private javax.swing.JMenu Help;
    private javax.swing.JMenuItem MD5;
    private javax.swing.JMenuItem SHA_1;
    private javax.swing.JMenuItem help;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
