/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ID.java
 *
 * Created on 25 mai 2010, 15:06:32
 */
package MAC;

import java.math.BigInteger;
import javax.swing.*;

/**
 *
 * @author choukri
 */
public class SHA1 extends javax.swing.JFrame {


    /** Creates new form ID */
    public String Ipad(int bit) {
        bit /= 8;
        byte[] a = new byte[bit];
        for (int i = 0; i < bit; i++) {
            a[i] = (byte) 0x36;
        }
        return new String(a);
    }

    public String Opad(int bit) {
        bit /= 8;
        byte[] a = new byte[bit];
        for (int i = 0; i < bit; i++) {
            a[i] = (byte) 0x5c;
        }
        return new String(a);
    }

    public String tohex(byte[] tab) {
        char a[] = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F'};
        int n = tab.length;
        String x = "";
        int c;
        for (int i = 0; i < n; i++) {
            c = tab[i];
            if (c < 0) {
                c += 256;
            }
            x += (a[c / 16]) + "" + (a[c % 16]);
        }
        return x;
    }

    public String Hasher(String x) {
        if (x.length() == 0) {
            JOptionPane.showMessageDialog(null, " Entrer votre clé SVP ", " Erreur ", 1);
            return null;
        }
        java.security.MessageDigest hash;
        try {
            hash = java.security.MessageDigest.getInstance("SHA");
        } catch (java.security.NoSuchAlgorithmException r) {
            return null;
        }
        hash.update(x.getBytes());
        byte[] digest = hash.digest();
        return tohex(digest);
    }

        BigInteger opad=new BigInteger(Opad(128).getBytes());
        BigInteger ipad=new BigInteger(Ipad(128).getBytes());

    public SHA1() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/testt/logo.png")).getImage());

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        message = new javax.swing.JLabel();
        clé = new javax.swing.JLabel();
        hmac = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        jtemps = new javax.swing.JLabel();
        txtclé = new javax.swing.JTextField();
        txthmac = new javax.swing.JTextField();
        temps = new javax.swing.JTextField();
        fermer = new javax.swing.JButton();
        calculer = new javax.swing.JButton();
        réinitialiser = new javax.swing.JButton();
        txtmessage = new javax.swing.JScrollPane();
        jtxtmessage = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        message.setForeground(new java.awt.Color(51, 153, 255));
        message.setText("Message");
        message.setName("Message"); // NOI18N

        clé.setForeground(new java.awt.Color(51, 153, 255));
        clé.setText("La clé");

        hmac.setForeground(new java.awt.Color(51, 153, 255));
        hmac.setText("HMAC-SHA_1");

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MAC/Application.jpg"))); // NOI18N
        image.setIconTextGap(0);

        jtemps.setForeground(new java.awt.Color(51, 153, 255));
        jtemps.setText("Temps d'execution");

        txtclé.setForeground(new java.awt.Color(255, 102, 0));

        txthmac.setForeground(new java.awt.Color(255, 102, 0));

        temps.setEditable(false);
        temps.setForeground(new java.awt.Color(255, 102, 0));

        fermer.setForeground(new java.awt.Color(51, 153, 255));
        fermer.setText("Fermer");
        fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fermerActionPerformed(evt);
            }
        });

        calculer.setForeground(new java.awt.Color(51, 153, 255));
        calculer.setText("Calculer");
        calculer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculerActionPerformed(evt);
            }
        });

        réinitialiser.setForeground(new java.awt.Color(51, 153, 255));
        réinitialiser.setText("Réinitialiser");
        réinitialiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                réinitialiserActionPerformed(evt);
            }
        });

        jtxtmessage.setColumns(20);
        jtxtmessage.setForeground(new java.awt.Color(255, 102, 0));
        jtxtmessage.setRows(5);
        txtmessage.setViewportView(jtxtmessage);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hmac)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txthmac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(message))
                                .addComponent(txtmessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(209, 209, 209)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(temps, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtclé, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addComponent(jtemps))
                                .addComponent(clé)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(calculer)
                            .addGap(176, 176, 176)
                            .addComponent(réinitialiser)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                            .addComponent(fermer))))
                .addGap(85, 85, 85))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(image)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clé)
                    .addComponent(message))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtclé, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jtemps)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(temps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtmessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(hmac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txthmac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fermer)
                    .addComponent(calculer)
                    .addComponent(réinitialiser))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fermerActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_fermerActionPerformed

    private void réinitialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_réinitialiserActionPerformed
        temps.setText("");
        txtclé.setText("");
        txthmac.setText("");
        jtxtmessage.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_réinitialiserActionPerformed

    private void calculerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculerActionPerformed
// TODO add your handling code here:
        String msg = jtxtmessage.getText();
        String cle = txtclé.getText();

        double q = System.nanoTime();
        BigInteger hcle =new BigInteger(Hasher(cle).getBytes());
        if (hcle == null) {
            temps.setText("");
            txtclé.setText("");
            txthmac.setText("");
            return;
        }
       //BigInteger BIhcle=new BigInteger(hcle.getBytes());
       //BigInteger BIipad=new BigInteger(ipad.getBytes());
       String A1=Hasher((hcle.xor(ipad)).toString()+""+msg);

       txthmac.setText(A1);






        q = System.nanoTime() - q;
        q /= 1000000000;
        temps.setText(q + "  Sec");
    }//GEN-LAST:event_calculerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SHA1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculer;
    private javax.swing.JLabel clé;
    private javax.swing.JButton fermer;
    private javax.swing.JLabel hmac;
    private javax.swing.JLabel image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jtemps;
    private javax.swing.JTextArea jtxtmessage;
    private javax.swing.JLabel message;
    private javax.swing.JButton réinitialiser;
    private javax.swing.JTextField temps;
    private javax.swing.JTextField txtclé;
    private javax.swing.JTextField txthmac;
    private javax.swing.JScrollPane txtmessage;
    // End of variables declaration//GEN-END:variables
}
