/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ID.java
 *
 * Created on 25 mai 2010, 15:06:32
 */
package brouillant;

import MAC.*;
import java.math.BigInteger;
import javax.swing.*;

/**
 *
 * @author choukri
 */
public class AES_test extends javax.swing.JFrame {


    /** Creates new form ID */
   public String StringToBinary(String text) {
        String textBinary = "";
        String s7 = "0000000", s6 = "000000", s5 = "00000", s4 = "0000", s3 = "000", s2 = "00", s1 = "0";


        int textLenth = text.length();
        //on decoupe le texte sous forme de carctères
        char[] c = text.toCharArray();
        //
        int[] b = new int[textLenth];
        String[] st = new String[textLenth];
        //
        for (int g = 0; g < textLenth; g++) {
            b[g] = (byte) c[g];//on converti chaque carctère a son code ascii
            st[g] = Integer.toBinaryString(b[g]);//on converti chaque code ascci sous sa forme binaire
            // System.out.println(st[g]);
            if (st[g].length() == 1) {
                st[g] = s7 + st[g];
            }//pour avoir des squences de 8 bits
            if (st[g].length() == 2) {
                st[g] = s6 + st[g];
            }//ca sera utile por le découpage pendant
            if (st[g].length() == 3) {
                st[g] = s5 + st[g];
            }//le déchifrement
            if (st[g].length() == 4) {
                st[g] = s4 + st[g];
            }
            if (st[g].length() == 5) {
                st[g] = s3 + st[g];
            }
            if (st[g].length() == 6) {
                st[g] = s2 + st[g];
            }
            if (st[g].length() == 7) {
                st[g] = s1 + st[g];
            }
            textBinary += st[g];
            //System.out.println(g+"\t"+st[g].toString());


        }
        //System.out.println(textBinary);
        return textBinary;
    }

    public String tohex(byte[] tab) {
        char a[] = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F'};
        int n = tab.length;
        String x = "";
        int c;
        for (int i = 0; i < n; i++) {
            c = tab[i];
            if (c < 0) {
                c += 256;
            }
            x += (a[c / 16]) + "" + (a[c % 16]);
        }
        return x;
    }

    public String Hasher(String x) {
        if (x.length() == 0) {
            JOptionPane.showMessageDialog(null, " Entrer votre clé SVP ", " Erreur ", 1);
            return null;
        }
        java.security.MessageDigest hash;
        try {
            hash = java.security.MessageDigest.getInstance("MD5");
        } catch (java.security.NoSuchAlgorithmException r) {
            return null;
        }
        hash.update(x.getBytes());
        byte[] digest = hash.digest();
        return tohex(digest);
    }

    public AES_test() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/testt/logo.png")).getImage());

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        message = new javax.swing.JLabel();
        hmac = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        jtemps = new javax.swing.JLabel();
        txthmac = new javax.swing.JTextField();
        temps = new javax.swing.JTextField();
        fermer = new javax.swing.JButton();
        calculer = new javax.swing.JButton();
        réinitialiser = new javax.swing.JButton();
        txtmessage = new javax.swing.JScrollPane();
        jtxtmessage = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        message.setForeground(new java.awt.Color(51, 153, 255));
        message.setText("Message");
        message.setName("Message"); // NOI18N

        hmac.setForeground(new java.awt.Color(51, 153, 255));
        hmac.setText("CBC-MAC avec DES");

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testt/scytale.gif"))); // NOI18N
        image.setIconTextGap(0);

        jtemps.setForeground(new java.awt.Color(51, 153, 255));
        jtemps.setText("Temps d'execution");

        txthmac.setForeground(new java.awt.Color(255, 102, 0));

        temps.setEditable(false);
        temps.setForeground(new java.awt.Color(255, 102, 0));

        fermer.setForeground(new java.awt.Color(51, 153, 255));
        fermer.setText("Fermer");
        fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fermerActionPerformed(evt);
            }
        });

        calculer.setForeground(new java.awt.Color(51, 153, 255));
        calculer.setText("Calculer");
        calculer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculerActionPerformed(evt);
            }
        });

        réinitialiser.setForeground(new java.awt.Color(51, 153, 255));
        réinitialiser.setText("Réinitialiser");
        réinitialiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                réinitialiserActionPerformed(evt);
            }
        });

        jtxtmessage.setColumns(20);
        jtxtmessage.setForeground(new java.awt.Color(255, 102, 0));
        jtxtmessage.setRows(5);
        txtmessage.setViewportView(jtxtmessage);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(image)
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hmac)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(calculer)
                                .addGap(172, 172, 172)
                                .addComponent(réinitialiser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                                .addComponent(fermer))
                            .addComponent(txthmac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(message)
                                    .addComponent(txtmessage, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(temps, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addComponent(jtemps))))
                        .addGap(85, 85, 85))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(message)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jtemps)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(temps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtmessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(hmac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txthmac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculer)
                    .addComponent(fermer)
                    .addComponent(réinitialiser))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fermerActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_fermerActionPerformed

    private void réinitialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_réinitialiserActionPerformed
        temps.setText("");
        txthmac.setText("");
        jtxtmessage.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_réinitialiserActionPerformed

    private void calculerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculerActionPerformed
// TODO add your handling code here:
        String msg = jtxtmessage.getText();
        String [] tab = null;
         double q = System.nanoTime();
        for(int i=0;i<msg.length();i++)
        {
            tab[i]=StringToBinary(msg);
        }
         
//        BigInteger hcle =new BigInteger(Hasher(cle).getBytes());
//        if (hcle == null) {
           // temps.setText("");
           // txthmac.setText("");
           // return;
//        }
       //BigInteger BIhcle=new BigInteger(hcle.getBytes());
       //BigInteger BIipad=new BigInteger(ipad.getBytes());
       String A1=Hasher(msg);

        txthmac.setText(A1);






        q = System.nanoTime() - q;
        q /= 1000000000;
        temps.setText(q + "  Sec");
    }//GEN-LAST:event_calculerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AES_test().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculer;
    private javax.swing.JButton fermer;
    private javax.swing.JLabel hmac;
    private javax.swing.JLabel image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jtemps;
    private javax.swing.JTextArea jtxtmessage;
    private javax.swing.JLabel message;
    private javax.swing.JButton réinitialiser;
    private javax.swing.JTextField temps;
    private javax.swing.JTextField txthmac;
    private javax.swing.JScrollPane txtmessage;
    // End of variables declaration//GEN-END:variables
}
